name: lowvr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi>=0.109.0
    - uvicorn[standard]>=0.27.0
    - pydantic>=2.5.0
    - orjson>=3.9.0
    - pyyaml>=6.0
    - wandb>=0.12.0
    - python-multipart>=0.0.6
